[package]
name = "pernixc_ir"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
pernixc_transitive_closure = { path = "../../base/transitive_closure" }
pernixc_serialize = { path = "../../base/serialize" }
pernixc_stable_hash = { path = "../../base/stable_hash" }
pernixc_arena = { path = "../../base/arena" }
pernixc_lexical = { path = "../../syntax/lexical" }
pernixc_semantic_element = { path = "../semantic_element" }
pernixc_term = { path = "../term" }
pernixc_symbol = { path = "../symbol" }
pernixc_target = { path = "../../base/target" }
pernixc_source_file = { path = "../../base/source_file" }
pernixc_query = { path = "../../base/query" }
pernixc_handler = { path = "../../base/handler" }
pernixc_diagnostic = { path = "../../base/diagnostic" }
pernixc_type_system = { path = "../type_system" }
pernixc_hash = { path = "../../base/hash" }
enum-as-inner = { workspace = true }
derive_more = { workspace = true }
getset = { workspace = true }
flexstr = { workspace = true }
bon = { workspace = true }

[lints]
workspace = true
