[package]
name = "pernixc_check"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
pernixc_diagnostic = { path = "../../base/diagnostic" }
pernixc_query = { path = "../../base/query" }
pernixc_target = { path = "../../base/target" }
pernixc_stable_hash = { path = "../../base/stable_hash" }
pernixc_serialize = { path = "../../base/serialize" }
pernixc_symbol_impl = { path = "../symbol_impl" }
pernixc_semantic_element_impl = { path = "../semantic_element_impl" }
pernixc_ir_impl = { path = "../ir_impl" }
pernixc_register = { path = "../../base/register" }

tokio = { workspace = true }

[lints]
workspace = true
