[package]
name = "pernixc_ir_impl"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
pernixc_diagnostic = { path = "../../base/diagnostic" }
pernixc_handler = { path = "../../base/handler" }
pernixc_target = { path = "../../base/target" }
pernixc_tokio = { path = "../../base/tokio" }
pernixc_source_file = { path = "../../base/source_file" }
pernixc_symbol = { path = "../symbol" }
pernixc_ir = { path = "../ir" }
pernixc_bind = { path = "../bind" }
pernixc_memory_checker = { path = "../memory_checker" }
pernixc_borrow_checker = { path = "../borrow_checker" }
pernixc_type_system = { path = "../type_system" }
pernixc_qbice = { path = "../../base/qbice" }
qbice = { workspace = true }
linkme = { workspace = true }
derive_more = { workspace = true }


[lints]
workspace = true
