[package]
name = "pernixc_target"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
arbitrary = ["dep:proptest"]

[dependencies]
pernixc_hash = { path = "../hash" }
pernixc_extend = { path = "../extend" }
pernixc_qbice.path = "../qbice"
derive-new = { workspace = true }
clap = { workspace = true }
enum-as-inner = { workspace = true }
flexstr = { workspace = true }
rand = { workspace = true }
siphasher = { workspace = true }
proptest = { workspace = true, optional = true }
qbice.workspace = true

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
