[package]
name = "pernixc_source_file"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
pernixc_arena = { path = "../arena" }
pernixc_target = { path = "../target" }
pernixc_extend = { path = "../extend" }
pernixc_qbice.path = "../qbice"
thiserror = { workspace = true }
dashmap = { workspace = true }
getset = { workspace = true }
codespan-reporting = { workspace = true }
fxhash = { workspace = true }
siphasher = { workspace = true }
rayon = { workspace = true }
qbice.workspace = true

[lints]
workspace = true
