[package]
name = "pernix_server"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
env_logger = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower-lsp = { workspace = true }
parking_lot = { workspace = true }
getset = { workspace = true }
derive_more = { workspace = true }
thiserror = { workspace = true }
by_address = { workspace = true }
serde = { workspace = true }

pernixc_source_file = { path = "../../compiler/base/source_file" }
pernixc_diagnostic = { path = "../../compiler/base/diagnostic" }
pernixc_lexical = { path = "../../compiler/syntax/lexical" }
pernixc_target = { path = "../../compiler/base/target" }
pernixc_query = { path = "../../compiler/base/query" }
pernixc_corelib = { path = "../../compiler/semantic/corelib" }
pernixc_register = { path = "../../compiler/base/register" }


[lints]
workspace = true
