[package]
name = "pernix_server"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
tower-lsp = { workspace = true }
getset = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
bon = { workspace = true }
fuzzy-matcher = { workspace = true }
backtrace = { workspace = true }
tokio-util.workspace = true
tracing-subscriber = { workspace = true }
tracing.workspace = true
qbice.workspace = true
linkme.workspace = true

pernixc_source_file = { path = "../../compiler/base/source_file" }
pernixc_diagnostic = { path = "../../compiler/base/diagnostic" }
pernixc_lexical = { path = "../../compiler/syntax/lexical" }
pernixc_target = { path = "../../compiler/base/target" }
pernixc_extend = { path = "../../compiler/base/extend" }
pernixc_hash = { path = "../../compiler/base/hash" }
pernixc_check = { path = "../../compiler/semantic/check" }
pernixc_corelib = { path = "../../compiler/semantic/corelib" }
pernixc_symbol = { path = "../../compiler/semantic/symbol" }
pernixc_syntax = { path = "../../compiler/syntax/syntax" }
pernixc_parser = { path = "../../compiler/syntax/parser" }
pernixc_resolution = { path = "../../compiler/semantic/resolution" }
pernixc_semantic_element = { path = "../../compiler/semantic/semantic_element" }
pernixc_term = { path = "../../compiler/semantic/term" }
pernixc_tokio = { path = "../../compiler/base/tokio" }
pernixc_qbice.path = "../../compiler/base/qbice"
pernixc_source_file_impl.path = "../../compiler/base/source_file_impl"
pernixc_lexical_impl.path = "../../compiler/syntax/lexical_impl"
pernixc_syntax_impl.path = "../../compiler/syntax/syntax_impl"


[lints]
workspace = true
