[package]
name = "pernixc_type_system"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
pernixc_target = { path = "../../base/target" }
pernixc_extend = { path = "../../base/extend" }
pernixc_arena = { path = "../../base/arena" }
pernixc_lexical = { path = "../../syntax/lexical" }
pernixc_diagnostic = { path = "../../base/diagnostic" }
pernixc_source_file = { path = "../../base/source_file" }
pernixc_handler = { path = "../../base/handler" }
pernixc_term = { path = "../term" }
pernixc_symbol = { path = "../symbol" }
pernixc_semantic_element = { path = "../semantic_element" }
thiserror = { workspace = true }
parking_lot = { workspace = true }
enum-as-inner = { workspace = true }
getset = { workspace = true }
derive-new = { workspace = true }
derive_more = { workspace = true }
rstest = { workspace = true }
bon = { workspace = true }


[dev-dependencies]
pernixc_symbol = { path = "../symbol", features = ["arbitrary"] }
pernixc_term = { path = "../term", features = ["arbitrary"] }
proptest = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
